[package]
name        = "uju-cw2-common"
version     = "0.1.0"
description = "A package for common utilities for CosmWasm 2.0 contracts"
authors     = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
cosmwasm-std = { workspace = true }
thiserror    = { workspace = true }
