[package]
name        = "uju-cw2-common"
version     = "0.3.1"
description = "A package for common utilities for CosmWasm 2.0 contracts"
authors     = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw2             = { workspace = true }
cw-utils        = { workspace = true }
semver          = { workspace = true }
sha2            = { workspace = true }
sylvia          = { workspace = true }
thiserror       = { workspace = true }
