[package]
name        = "uju-index-query"
version     = "0.1.0"
description = "A package for common utilities for CosmWasm 2.0 contracts"
authors     = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }
