[package]
name        = "uju-cw2-nft"
version     = "0.1.0"
description = "A package for interacting with NFTs in CosmWasm 2.0 contracts"
authors     = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-utils        = { workspace = true }
thiserror       = { workspace = true }
uju-cw2-common  = { workspace = true }
